name: build vsix
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'ex. 0.0.1'
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: 'ex. 0.0.1'
    outputs:
      artifact-name:
        value: vsix-artifact
jobs:
  validate-input:
    uses: ./.github/workflows/validate-version-format.yml
    with:
      version: ${{ inputs.version }}
  build-server:
    uses: ./.github/workflows/build-server.yml
    needs: [validate-input]
    with:
      version: ${{ inputs.version }}
  build-client:
    uses: ./.github/workflows/build-client.yml
    needs: [validate-input]
    with:
      version: ${{ inputs.version }}
  build-vsix:
    runs-on: ubuntu-latest
    needs: [build-server, build-client]
    env:
      VSCE_VERSION: 3.2.1
      NODE_VERSION: 22
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # Download server apps
      - name: Download server artifact for windows x86_64
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-server.outputs.artifact-windows-x86-64 }}
          path: target/windows-x86-64/release/
      - name: Download server artifact for linux x86_64
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-server.outputs.artifact-linux-x86-64 }}
          path: target/linux-x86-64/release/
      - name: Download server artifact for macos arm64
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-server.outputs.artifact-macos-arm64 }}
          path: target/macos-arm64/release/
      #
      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-client.outputs.artifact-name }}
          path: dist/
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache vsce
        id: cache-vsce
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/vsce
            /usr/local/lib/node_modules/@vscode
          key: vsce-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.VSCE_VERSION }}
      - name: Install vsce
        if: steps.cache-vsce.outputs.cache-hit != 'true'
        run: npm install -g @vscode/vsce@
      - name: Add execution permission
        run: chmod -R +x target/
      - name: Package vsix
        run: vsce package -o dist/
      - name: Archive vsix
        uses: actions/upload-artifact@v4
        with:
          name: vsix-artifact
          path: dist/*.vsix
