name: Validate Version Format
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  validate-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Validate version format
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION;
            const versionRegex = /^\d+\.\d+\.\d+$/;

            if (!versionRegex.test(version)) {
              core.setFailed(`Version "${version}" is not in the *.*.* format.`);
            } else {
              console.log(`Version "${version}" is in the correct format.`);
            }
        env:
          VERSION: ${{ inputs.version }}
